# -*- coding: utf-8 -*-
"""mfo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mzpGdwVybx6ymiwAecvbrUh0-hbO36oS
"""

# ----------------------------
# Moth-Flame Optimization (MFO) Full Script
# Save as MFO.py
# ----------------------------

import numpy as np
import matplotlib.pyplot as plt

# ----------------------------
# Benchmark Functions
# ----------------------------
def sphere_function(x):
    return np.sum(x ** 2)

def rastrigin_function(x):
    A = 10
    return A * len(x) + np.sum(x**2 - A * np.cos(2 * np.pi * x))

# ----------------------------
# Initialize Moths
# ----------------------------
def initialize_moths(num_moths, dim, lb, ub):
    return np.random.uniform(lb, ub, (num_moths, dim))

# ----------------------------
# Moth-Flame Optimization
# ----------------------------
def moth_flame_optimization(obj_func, lb, ub, dim, num_moths=30, max_iter=100):
    # Initialize moths
    moths = initialize_moths(num_moths, dim, lb, ub)
    fitness = np.array([obj_func(m) for m in moths])

    # Sort moths
    sorted_indices = np.argsort(fitness)
    flames = moths[sorted_indices].copy()
    flame_fitness = fitness[sorted_indices].copy()

    best_solution = flames[0].copy()
    best_fitness = flame_fitness[0]

    convergence_curve = []

    for t in range(max_iter):
        num_flames = round(num_moths - t * ((num_moths - 1) / max_iter))
        for i in range(num_moths):
            for j in range(dim):
                distance = abs(flames[i % num_flames, j] - moths[i, j])
                b = 1
                r = np.random.uniform(-1, 1)
                moths[i, j] = distance * np.exp(b * r) * np.cos(2 * np.pi * r) + flames[i % num_flames, j]

        moths = np.clip(moths, lb, ub)
        fitness = np.array([obj_func(m) for m in moths])

        combined = np.vstack((flames, moths))
        combined_fitness = np.hstack((flame_fitness, fitness))

        indices = np.argsort(combined_fitness)
        flames = combined[indices][:num_moths]
        flame_fitness = combined_fitness[indices][:num_moths]

        if flame_fitness[0] < best_fitness:
            best_fitness = flame_fitness[0]
            best_solution = flames[0].copy()

        convergence_curve.append(best_fitness)

    return best_solution, best_fitness, convergence_curve

# ----------------------------
# Problem Settings
# ----------------------------
dimension = 10
lower_bound = -5.12
upper_bound = 5.12
iterations = 100
moths = 30

# ----------------------------
# Run MFO on Sphere Function
# ----------------------------
best_sol_sphere, best_fit_sphere, curve_sphere = moth_flame_optimization(
    sphere_function, lower_bound, upper_bound, dimension, moths, iterations
)

print("Sphere Best Solution:", best_sol_sphere)
print("Sphere Best Fitness:", best_fit_sphere)

plt.figure()
plt.plot(curve_sphere)
plt.title("MFO Convergence Curve - Sphere")
plt.xlabel("Iteration")
plt.ylabel("Best Fitness")
plt.grid(True)
plt.savefig("MFO_Sphere_Convergence.png")
plt.show()

# ----------------------------
# Run MFO on Rastrigin Function
# ----------------------------
best_sol_rastrigin, best_fit_rastrigin, curve_rastrigin = moth_flame_optimization(
    rastrigin_function, lower_bound, upper_bound, dimension, moths, iterations
)

print("Rastrigin Best Solution:", best_sol_rastrigin)
print("Rastrigin Best Fitness:", best_fit_rastrigin)

plt.figure(figsize=(8,5))
plt.plot(curve_rastrigin, 'r-', linewidth=2)
plt.title("MFO Convergence Curve - Rastrigin")
plt.xlabel("Iteration")
plt.ylabel("Fitness Value")
plt.grid(True)
plt.savefig("MFO_Rastrigin_Convergence.png")
plt.show()